format_version: 2
pipelines:
  my-pipeline:
    group: my-group
    materials:
      git-repo:
        git: https://github.com/gotham-learning/vue-gotham-todo.git
        branch: master
    stages:
      - first-stage:
          jobs:
            build:
              tasks:
                - exec:
                    command: gotham-todo/build.sh
