format_version: 2
pipelines:
  my-pipeline:
    group: my-group
    materials:
      git-repo:
        git: https://github.com/gotham-learning/vue-gotham-todo.git
        branch: master
    stages:
      - first-stage:
          jobs:
            list:
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - .
       - second-stage:
          jobs:
            list:
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - .
